/**
 * season_data.js - Каталоги свободных ЧВК, организаций и автономий для Сезона 28
 */

export const PMC_AND_ORGS = [
  // --- ГОСУДАРСТВЕННЫЕ ОРГАНИЗАЦИИ (8) ---
  {
    key: 'pmc_wagner',
    name: 'Вагнер',
    flag: '🇷🇺',
    host_country: 'Россия',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Россия',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Россия',
      capital: 850000000,
      personnel: 25000,
      specialization: 'Штурмовые операции, дальние экспедиции и охрана месторождений',
      contract_rate: 'От 18 млн $/мес',
      readiness: 'Высокая (100%)',
      balance: 140000000,
      support: 90.0,
      equipment: 'Тяжёлая бронетехника, артиллерия, РСЗО, штурмовая авиация'
    }
  },
  {
    key: 'pmc_patriot',
    name: 'Патриот',
    flag: '🇷🇺',
    host_country: 'Россия',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Россия',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Россия',
      capital: 600000000,
      personnel: 15000,
      specialization: 'Высокотехнологичные спецоперации, охрана первых лиц и VIP-объектов',
      contract_rate: 'От 15 млн $/мес',
      readiness: 'Высокая (100%)',
      balance: 110000000,
      support: 92.0,
      equipment: 'Новейшая бронетехника, системы РЭБ, разведывательные комплексы БЛА'
    }
  },
  {
    key: 'pmc_redut',
    name: 'Редут',
    flag: '🇷🇺',
    host_country: 'Россия',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Россия',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Россия',
      capital: 450000000,
      personnel: 12000,
      specialization: 'Охрана критической инфраструктуры, трубопроводов и промышленных узлов',
      contract_rate: 'От 12 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 95000000,
      support: 88.0,
      equipment: 'Бронированные автомобили, мобильные расчеты ПВО, дроны-камикадзе'
    }
  },
  {
    key: 'pmc_rsb_group',
    name: 'RSB-Group',
    flag: '🇷🇺',
    host_country: 'Россия',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Россия',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Россия',
      capital: 320000000,
      personnel: 8000,
      specialization: 'Морская безопасность, антипиратские конвои, гуманитарное разминирование',
      contract_rate: 'От 9 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 70000000,
      support: 91.0,
      equipment: 'Скоростные сторожевые катера, робототехнические комплексы разминирования'
    }
  },
  {
    key: 'pmc_gardservice',
    name: 'GardService',
    flag: '🇧🇾',
    host_country: 'Беларусь',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Беларусь',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Беларусь',
      capital: 280000000,
      personnel: 6500,
      specialization: 'Охрана правительственных объектов, сопровождение транзитных грузов',
      contract_rate: 'От 7 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 60000000,
      support: 89.0,
      equipment: 'Легкая бронетехника, спецтранспорт, стрелковые комплексы повышенной точности'
    }
  },
  {
    key: 'pmc_huaxin_zhongan',
    name: 'Huaxin Zhongan',
    flag: '🇨🇳',
    host_country: 'Китай',
    continent: 'Азия',
    itemType: 'pmc',
    typeLabel: 'Организация · Китай',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Китай',
      capital: 750000000,
      personnel: 22000,
      specialization: 'Безопасность проектов «Пояс и путь», защита морских торговых караванов',
      contract_rate: 'От 16 млн $/мес',
      readiness: 'Высокая (100%)',
      balance: 160000000,
      support: 94.0,
      equipment: 'Океанские эскортные суда, антидроновые ружья, защищенная спутниковая связь'
    }
  },
  {
    key: 'pmc_dewe_security',
    name: 'DeWe Security',
    flag: '🇨🇳',
    host_country: 'Китай',
    continent: 'Азия',
    itemType: 'pmc',
    typeLabel: 'Организация · Китай',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Китай',
      capital: 550000000,
      personnel: 14000,
      specialization: 'Защита зарубежных инфраструктурных активов, охрана рудников и нефтяных хабов',
      contract_rate: 'От 11 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 120000000,
      support: 92.0,
      equipment: 'Бронированные вездеходы, комплексы видеоаналитики периметра, кибербезопасность'
    }
  },
  {
    key: 'pmc_sadat',
    name: 'SADAT',
    flag: '🇹🇷',
    host_country: 'Турция',
    continent: 'Азия',
    itemType: 'pmc',
    typeLabel: 'Организация · Турция',
    org_category: 'Государственные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Турция',
      capital: 500000000,
      personnel: 10000,
      specialization: 'Международный оборонный консалтинг, военная подготовка и спецоперации',
      contract_rate: 'От 14 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 500000000,
      support: 90.0,
      equipment: 'Тактическое вооружение, ударные БЛА Bayraktar, специализированные полигоны'
    }
  },

  // --- ЧАСТНЫЕ ОРГАНИЗАЦИИ (18) ---
  {
    key: 'pmc_academi',
    name: 'Academi',
    flag: '🇺🇸',
    host_country: 'США',
    continent: 'Северная Америка',
    itemType: 'pmc',
    typeLabel: 'Организация · США',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'США',
      capital: 1200000000,
      personnel: 20000,
      specialization: 'VIP-охрана, спецоперации, комплексная подготовка тактических групп',
      contract_rate: 'От 25 млн $/мес',
      readiness: 'Максимальная (100%)',
      balance: 220000000,
      support: 86.0,
      equipment: 'Тактическая авиация, БЛА, защищённые бронеавтомобили MRAP'
    }
  },
  {
    key: 'pmc_draken',
    name: 'Draken International',
    flag: '🇺🇸',
    host_country: 'США',
    continent: 'Северная Америка',
    itemType: 'pmc',
    typeLabel: 'Организация · США',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'США',
      capital: 900000000,
      personnel: 4500,
      specialization: 'Частная тактическая авиация, агрессор-эскадрильи, авиационная поддержка',
      contract_rate: 'От 20 млн $/мес',
      readiness: 'Высокая (100%)',
      balance: 180000000,
      support: 92.0,
      equipment: 'Флот боевых истребителей Mirage F1, A-4 Skyhawk, L-159 ALCA'
    }
  },
  {
    key: 'pmc_dyncorp',
    name: 'DynCorp',
    flag: '🇺🇸',
    host_country: 'США',
    continent: 'Северная Америка',
    itemType: 'pmc',
    typeLabel: 'Организация · США',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'США',
      capital: 950000000,
      personnel: 18000,
      specialization: 'Военная логистика, ремонт боевой техники, обучение силовых структур',
      contract_rate: 'От 19 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 150000000,
      support: 88.0,
      equipment: 'Парк военно-транспортных вертолётов, мобильные базы полевого обслуживания'
    }
  },
  {
    key: 'pmc_triple_canopy',
    name: 'Triple Canopy',
    flag: '🇺🇸',
    host_country: 'США',
    continent: 'Северная Америка',
    itemType: 'pmc',
    typeLabel: 'Организация · США',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'США',
      capital: 700000000,
      personnel: 11000,
      specialization: 'Охрана дипломатических миссий, сопровождение конвоев высокой опасности',
      contract_rate: 'От 15 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 130000000,
      support: 89.0,
      equipment: 'Тяжелобронированные SUV, системы подавления радиоуправляемых фугасов'
    }
  },
  {
    key: 'pmc_mpri',
    name: 'MPRI',
    flag: '🇺🇸',
    host_country: 'США',
    continent: 'Северная Америка',
    itemType: 'pmc',
    typeLabel: 'Организация · США',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'США',
      capital: 520000000,
      personnel: 5000,
      specialization: 'Стратегический военный консалтинг, реформирование армейских штабов',
      contract_rate: 'От 12 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 95000000,
      support: 90.0,
      equipment: 'Аналитические центры, симуляторы командно-штабных учений'
    }
  },
  {
    key: 'pmc_g4s',
    name: 'G4S',
    flag: '🇬🇧',
    host_country: 'Великобритания',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Великобритания',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Великобритания',
      capital: 1400000000,
      personnel: 35000,
      specialization: 'Глобальная корпоративная безопасность, инкассация, охрана портов и границ',
      contract_rate: 'От 22 млн $/мес',
      readiness: 'Высокая (100%)',
      balance: 240000000,
      support: 91.0,
      equipment: 'Спутниковые командные хабы, системы биометрического контроля, бронетранспорт'
    }
  },
  {
    key: 'pmc_aegis',
    name: 'Aegis Defence Services',
    flag: '🇬🇧',
    host_country: 'Великобритания',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Великобритания',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Великобритания',
      capital: 480000000,
      personnel: 7500,
      specialization: 'Вооружённая защита миссий, оценка геополитических рисков и кризис-менеджмент',
      contract_rate: 'От 10 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 85000000,
      support: 88.0,
      equipment: 'Бронированные автомобили, средства радиоперехвата и защищенной связи'
    }
  },
  {
    key: 'pmc_erinys',
    name: 'Erinys',
    flag: '🇬🇧',
    host_country: 'Великобритания',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Великобритания',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Великобритания',
      capital: 360000000,
      personnel: 6000,
      specialization: 'Охрана объектов ТЭК, защита магистральных трубопроводов в зонах конфликтов',
      contract_rate: 'От 8 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 65000000,
      support: 87.0,
      equipment: 'Патрульная авиация лёгкого класса, сенсоры периметра с автономным питанием'
    }
  },
  {
    key: 'pmc_geos',
    name: 'GEOS',
    flag: '🇫🇷',
    host_country: 'Франция',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Франция',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Франция',
      capital: 390000000,
      personnel: 5500,
      specialization: 'Бизнес-разведка, эвакуация экспатов из горячих точек, промышленный аудит',
      contract_rate: 'От 9 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 75000000,
      support: 89.0,
      equipment: 'Специальный транспорт, средства скрытого мониторинга и киберзащиты'
    }
  },
  {
    key: 'pmc_paladin',
    name: 'Paladin Group',
    flag: '🇦🇺',
    host_country: 'Австралия',
    continent: 'Австралия и Океания',
    itemType: 'pmc',
    typeLabel: 'Организация · Австралия',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Австралия',
      capital: 340000000,
      personnel: 5000,
      specialization: 'Охрана удалённых островных баз, безопасность лагерей и гуманитарных зон',
      contract_rate: 'От 7.5 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 60000000,
      support: 88.0,
      equipment: 'Внедорожники повышенной проходимости, терминалы спутниковой связи Starlink'
    }
  },
  {
    key: 'pmc_unity',
    name: 'Unity Resources Group',
    flag: '🇦🇺',
    host_country: 'Австралия',
    continent: 'Австралия и Океания',
    itemType: 'pmc',
    typeLabel: 'Организация · Австралия',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Австралия',
      capital: 380000000,
      personnel: 6500,
      specialization: 'Охрана критических объектов в Азии и на Ближнем Востоке, эскорт конвоев',
      contract_rate: 'От 8.5 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 70000000,
      support: 87.0,
      equipment: 'Бронированные грузовики, средства тактической медицины и эвакуации'
    }
  },
  {
    key: 'pmc_asgaard',
    name: 'Asgaard',
    flag: '🇩🇪',
    host_country: 'Германия',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Германия',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Германия',
      capital: 310000000,
      personnel: 4000,
      specialization: 'Консалтинг силовых ведомств, контртерроризм, подготовка телохранителей',
      contract_rate: 'От 7 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 55000000,
      support: 90.0,
      equipment: 'Немецкое тактическое стрелковое оружие, снаряжение радиационной и химзащиты'
    }
  },
  {
    key: 'pmc_uc_global',
    name: 'UC GLOBAL',
    flag: '🇪🇸',
    host_country: 'Испания',
    continent: 'Европа',
    itemType: 'pmc',
    typeLabel: 'Организация · Испания',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Испания',
      capital: 260000000,
      personnel: 3500,
      specialization: 'Контрнаблюдение, морская безопасность, электронная разведка и VIP-эскорт',
      contract_rate: 'От 6 млн $/мес',
      readiness: 'Высокая (85%)',
      balance: 48000000,
      support: 86.0,
      equipment: 'Комплексы акустического контроля, скоростные катера-перехватчики'
    }
  },
  {
    key: 'pmc_global_cst',
    name: 'Global CST',
    flag: '🇮🇱',
    host_country: 'Израиль',
    continent: 'Азия',
    itemType: 'pmc',
    typeLabel: 'Организация · Израиль',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Израиль',
      capital: 580000000,
      personnel: 7000,
      specialization: 'Модернизация армий, внедрение израильских методик разведки и тактики боя',
      contract_rate: 'От 14 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 115000000,
      support: 93.0,
      equipment: 'Высокоточные оптико-электронные системы, тактические квадрокоптеры'
    }
  },
  {
    key: 'pmc_sttep',
    name: 'STTEP',
    flag: '🇿🇦',
    host_country: 'ЮАР',
    continent: 'Африка',
    itemType: 'pmc',
    typeLabel: 'Организация · ЮАР',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'ЮАР',
      capital: 370000000,
      personnel: 6000,
      specialization: 'Противопартизанские операции, выслеживание в саванне и джунглях, подготовка войск',
      contract_rate: 'От 8 млн $/мес',
      readiness: 'Высокая (90%)',
      balance: 68000000,
      support: 89.0,
      equipment: 'Ударные вертолёты Ми-24, боевые машины повышенной противоминной стойкости'
    }
  },
  {
    key: 'pmc_executive_outcomes',
    name: 'Executive Outcomes',
    flag: '🇿🇦',
    host_country: 'ЮАР',
    continent: 'Африка',
    itemType: 'pmc',
    typeLabel: 'Организация · ЮАР',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'ЮАР',
      capital: 490000000,
      personnel: 9000,
      specialization: 'Полномасштабные общевойсковые операции, подавление мятежей, штурмовые рейды',
      contract_rate: 'От 13 млн $/мес',
      readiness: 'Высокая (95%)',
      balance: 90000000,
      support: 91.0,
      equipment: 'Бронетехника Ratel и Casspir, штурмовая фронтовая авиация'
    }
  },
  {
    key: 'pmc_gardaworld',
    name: 'GardaWorld',
    flag: '🇨🇦',
    host_country: 'Канада',
    continent: 'Северная Америка',
    itemType: 'pmc',
    typeLabel: 'Организация · Канада',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Канада',
      capital: 1100000000,
      personnel: 28000,
      specialization: 'Защита дипломатов, охрана золотых приисков и рудников, бронированная логистика',
      contract_rate: 'От 21 млн $/мес',
      readiness: 'Высокая (100%)',
      balance: 200000000,
      support: 92.0,
      equipment: 'Крупный флот бронемашин, оперативные центры реагирования на инциденты'
    }
  },
  {
    key: 'pmc_defion',
    name: 'Defion Internacional',
    flag: '🇵🇪',
    host_country: 'Перу',
    continent: 'Южная Америка',
    itemType: 'pmc',
    typeLabel: 'Организация · Перу',
    org_category: 'Частные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Перу',
      capital: 220000000,
      personnel: 4500,
      specialization: 'Рекрутинг и подготовка контрактников для миссий в зонах повышенного риска',
      contract_rate: 'От 5 млн $/мес',
      readiness: 'Базовая (85%)',
      balance: 38000000,
      support: 84.0,
      equipment: 'Стандартное армейское стрелковое вооружение, тактическая экипировка'
    }
  },

  // --- МЕЖДУНАРОДНЫЕ ОРГАНИЗАЦИИ (2) ---
  {
    key: 'org_un',
    name: 'ООН',
    flag: '🇺🇳',
    host_country: 'Международная',
    continent: 'Глобально',
    itemType: 'pmc',
    typeLabel: 'Международная организация',
    org_category: 'Международные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Международная',
      capital: 3500000000,
      personnel: 90000,
      specialization: 'Миротворческие миссии, защита гуманитарных коридоров, глобальный арбитраж',
      contract_rate: 'Резолюции Совета Безопасности',
      readiness: 'Глобальная (100%)',
      balance: 500000000,
      support: 95.0,
      equipment: 'Миротворческие базы «голубых касок», транспортная авиация, гуманитарные конвои'
    }
  },
  {
    key: 'org_gate',
    name: 'GATE',
    flag: '🇺🇳',
    host_country: 'Международная',
    continent: 'Глобально',
    itemType: 'pmc',
    typeLabel: 'Международный альянс',
    org_category: 'Международные организации',
    isTaken: false,
    data: {
      isPMC: true,
      isTaken: false,
      host_country: 'Международная',
      capital: 1800000000,
      personnel: 24000,
      specialization: 'Мониторинг трансграничных угроз, контроль нераспространения оружия, киберщит',
      contract_rate: 'Коалиционное финансирование',
      readiness: 'Высокая (100%)',
      balance: 320000000,
      support: 93.0,
      equipment: 'Спутниковая группировка раннего оповещения, мобильные группы спецреагирования'
    }
  }
];


export const FREE_AUTONOMIES = [
  // --- РОССИЯ (9) ---
  {
    key: 'auto_yakutia',
    name: 'Якутия',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Якутск',
      gdp: 26000000000,
      population: 997000,
      birth_rate: 12.8,
      resource_index: 10,
      balance: 4200000000,
      support: 92.0,
      corruption: 6.2,
      specialization: 'Мировая добыча алмазов, золота, коксующегося угля и природного газа'
    }
  },
  {
    key: 'auto_komi',
    name: 'Коми',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Сыктывкар',
      gdp: 12500000000,
      population: 730000,
      birth_rate: 9.4,
      resource_index: 9,
      balance: 1900000000,
      support: 88.0,
      corruption: 7.1,
      specialization: 'Тимано-Печорская нефтегазовая провинция, лесопромышленный комплекс, уголь'
    }
  },
  {
    key: 'auto_chukotka',
    name: 'Чукотка',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Автономный округ в составе Российской Федерации',
      capital: 'Анадырь',
      gdp: 3200000000,
      population: 47000,
      birth_rate: 11.2,
      resource_index: 9,
      balance: 850000000,
      support: 90.0,
      corruption: 5.4,
      specialization: 'Добыча золота, серебра, платины, контроль трассы Севморпути'
    }
  },
  {
    key: 'auto_chechnya',
    name: 'Чечня',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Грозный',
      gdp: 4500000000,
      population: 1510000,
      birth_rate: 20.1,
      resource_index: 7,
      balance: 1100000000,
      support: 96.0,
      corruption: 8.5,
      specialization: 'Нефтедобыча, строительный сектор, высочайший мобилизационный потенциал'
    }
  },
  {
    key: 'auto_dagestan',
    name: 'Дагестан',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Махачкала',
      gdp: 11800000000,
      population: 3180000,
      birth_rate: 14.9,
      resource_index: 8,
      balance: 1800000000,
      support: 91.0,
      corruption: 8.9,
      specialization: 'Каспийские порты, коридор «Север — Юг», гидроэнергетика, виноградарство'
    }
  },
  {
    key: 'auto_kbr',
    name: 'Кабардино-Балкария',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Нальчик',
      gdp: 3800000000,
      population: 890000,
      birth_rate: 11.8,
      resource_index: 7,
      balance: 620000000,
      support: 89.0,
      corruption: 7.8,
      specialization: 'Вольфрамо-молибденовые месторождения, туризм Приэльбрусья, гидроэнергетика'
    }
  },
  {
    key: 'auto_alania',
    name: 'Северная Осетия',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Владикавказ',
      gdp: 3100000000,
      population: 687000,
      birth_rate: 11.0,
      resource_index: 6,
      balance: 510000000,
      support: 90.0,
      corruption: 7.4,
      specialization: 'Цветная металлургия, Военно-Грузинская дорога, транскавказский транзит'
    }
  },
  {
    key: 'auto_karelia',
    name: 'Карелия',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Петрозаводск',
      gdp: 6200000000,
      population: 533000,
      birth_rate: 7.9,
      resource_index: 8,
      balance: 920000000,
      support: 86.0,
      corruption: 6.8,
      specialization: 'Железнорудные окатыши, целлюлозно-бумажное производство, гранит и шунгит'
    }
  },
  {
    key: 'auto_tyva',
    name: 'Тыва',
    flag: '🇷🇺',
    host_country: 'Россия',
    group_category: 'Россия',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Россия',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Россия',
      status: 'Республика в составе Российской Федерации',
      capital: 'Кызыл',
      gdp: 1400000000,
      population: 336000,
      birth_rate: 18.5,
      resource_index: 8,
      balance: 310000000,
      support: 91.0,
      corruption: 8.0,
      specialization: 'Улуг-Хемский угольный бассейн, полиметаллические руды, животноводство'
    }
  },

  // --- КИТАЙ (7) ---
  {
    key: 'auto_tibet',
    name: 'Тибет',
    flag: '🇨🇳',
    host_country: 'Китай',
    group_category: 'Китай',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Китай',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Китай',
      status: 'Тибетский автономный район КНР',
      capital: 'Лхаса',
      gdp: 31000000000,
      population: 3660000,
      birth_rate: 12.0,
      resource_index: 8,
      balance: 4800000000,
      support: 85.0,
      corruption: 6.5,
      specialization: 'Каскады высокогорных ГЭС на реках Брахмапутра и Меконг, медные рудники'
    }
  },
  {
    key: 'auto_xinjiang',
    name: 'Синьзян',
    flag: '🇨🇳',
    host_country: 'Китай',
    group_category: 'Китай',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Китай',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Китай',
      status: 'Синьцзян-Уйгурский автономный район КНР',
      capital: 'Урумчи',
      gdp: 260000000000,
      population: 25850000,
      birth_rate: 8.5,
      resource_index: 10,
      balance: 35000000000,
      support: 87.0,
      corruption: 7.2,
      specialization: 'Таримский нефтегазоносный бассейн, солнечная энергетика, сухопутный коридор в Европу'
    }
  },
  {
    key: 'auto_inner_mongolia',
    name: 'Внутренняя Монголия',
    flag: '🇨🇳',
    host_country: 'Китай',
    group_category: 'Китай',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Китай',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Китай',
      status: 'Автономный район Внутренняя Монголия КНР',
      capital: 'Хух-Хото',
      gdp: 340000000000,
      population: 24000000,
      birth_rate: 7.2,
      resource_index: 10,
      balance: 42000000000,
      support: 89.0,
      corruption: 7.0,
      specialization: 'Месторождение редкоземельных металлов Баян-Обо (70% запасов КНР), углехимия'
    }
  },
  {
    key: 'auto_guangxi',
    name: 'Гуанси-Чжуанский район',
    flag: '🇨🇳',
    host_country: 'Китай',
    group_category: 'Китай',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Китай',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Китай',
      status: 'Гуанси-Чжуанский автономный район КНР',
      capital: 'Наньнин',
      gdp: 380000000000,
      population: 50400000,
      birth_rate: 9.1,
      resource_index: 8,
      balance: 46000000000,
      support: 88.0,
      corruption: 7.5,
      specialization: 'Глубоководные порты залива Бакбо, торговый шлюз со странами АСЕАН, алюминий'
    }
  },
  {
    key: 'auto_ningxia',
    name: 'Нинся-Хуэйский',
    flag: '🇨🇳',
    host_country: 'Китай',
    group_category: 'Китай',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Китай',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Китай',
      status: 'Нинся-Хуэйский автономный район КНР',
      capital: 'Иньчуань',
      gdp: 75000000000,
      population: 7280000,
      birth_rate: 8.8,
      resource_index: 7,
      balance: 9500000000,
      support: 87.0,
      corruption: 6.9,
      specialization: 'Современная углехимия, кластер зеленой энергетики, крупнейшие дата-центры'
    }
  },
  {
    key: 'auto_macau',
    name: 'Макао',
    flag: '🇲🇴',
    host_country: 'Китай',
    group_category: 'Китай',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Китай',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Китай',
      status: 'Специальный административный район Аомынь (Макао)',
      capital: 'Макао',
      gdp: 47000000000,
      population: 683000,
      birth_rate: 6.2,
      resource_index: 5,
      balance: 18000000000,
      support: 92.0,
      corruption: 4.8,
      specialization: 'Мировая столица туризма и развлечений, офшорные финансы, зона беспошлинной торговли'
    }
  },
  {
    key: 'auto_hong_kong',
    name: 'Гонконг',
    flag: '🇭🇰',
    host_country: 'Китай',
    group_category: 'Китай',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Китай',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Китай',
      status: 'Специальный административный район Сянган (Гонконг)',
      capital: 'Гонконг',
      gdp: 382000000000,
      population: 7500000,
      birth_rate: 5.8,
      resource_index: 5,
      balance: 110000000000,
      support: 90.0,
      corruption: 3.5,
      specialization: 'Ведущий финансовый центр Азии, фондовая биржа HKEX, глобальный морской логистический узел'
    }
  },

  // --- США (3) ---
  {
    key: 'auto_texas',
    name: 'Техас',
    flag: '🇺🇸',
    host_country: 'США',
    group_category: 'США',
    continent: 'Северная Америка',
    itemType: 'autonomy',
    typeLabel: 'Автономия · США',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'США',
      status: 'Штат Одинокой звезды с расширенными конституционными правами',
      capital: 'Остин',
      gdp: 2400000000000,
      population: 30000000,
      birth_rate: 13.5,
      resource_index: 10,
      balance: 180000000000,
      support: 92.0,
      corruption: 4.2,
      specialization: 'Сланцевая нефть Пермского бассейна, СПГ-терминалы Мексиканского залива, аэрокосмос'
    }
  },
  {
    key: 'auto_california',
    name: 'Калифорния',
    flag: '🇺🇸',
    host_country: 'США',
    group_category: 'США',
    continent: 'Северная Америка',
    itemType: 'autonomy',
    typeLabel: 'Автономия · США',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'США',
      status: 'Штат США с крупнейшей экономикой',
      capital: 'Сакраменто',
      gdp: 3890000000000,
      population: 39000000,
      birth_rate: 11.2,
      resource_index: 9,
      balance: 210000000000,
      support: 91.0,
      corruption: 4.5,
      specialization: 'Кремниевая долина (IT и ИИ), биотехнологии, аэрокосмическая индустрия, порты'
    }
  },
  {
    key: 'auto_alaska',
    name: 'Аляска',
    flag: '🇺🇸',
    host_country: 'США',
    group_category: 'США',
    continent: 'Северная Америка',
    itemType: 'autonomy',
    typeLabel: 'Автономия · США',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'США',
      status: 'Арктический штат США с суверенным постоянным фондом',
      capital: 'Джуно',
      gdp: 65000000000,
      population: 733000,
      birth_rate: 12.3,
      resource_index: 10,
      balance: 78000000000,
      support: 89.0,
      corruption: 3.9,
      specialization: 'Нефтяные месторождения Прадхо-Бей, Трансаляскинский нефтепровод, стратегический форпост'
    }
  },

  // --- ДРУГИЕ ГОСУДАРСТВА (10) ---
  {
    key: 'auto_gagauzia',
    name: 'Гагаузия',
    flag: '🇲🇩',
    host_country: 'Молдова',
    group_category: 'Другие государства',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Молдова',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Молдова',
      status: 'Автономное территориальное образование Гагаузия (Гагауз Ери)',
      capital: 'Комрат',
      gdp: 600000000,
      population: 135000,
      birth_rate: 9.8,
      resource_index: 6,
      balance: 85000000,
      support: 93.0,
      corruption: 7.9,
      specialization: 'Агропромышленный экспорт, элитное виноделие, зерновое хозяйство'
    }
  },
  {
    key: 'auto_kurdistan',
    name: 'Курдистан',
    flag: '🇮🇶',
    host_country: 'Ирак',
    group_category: 'Другие государства',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Ирак',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Ирак',
      status: 'Курдский автономный регион с конституционной армией (Пешмерга)',
      capital: 'Эрбиль',
      gdp: 32000000000,
      population: 6170000,
      birth_rate: 19.5,
      resource_index: 9,
      balance: 4500000000,
      support: 94.0,
      corruption: 8.8,
      specialization: 'Добыча и экспорт нефти через трубопровод Джейхан, силы безопасности Пешмерга'
    }
  },
  {
    key: 'auto_catalonia',
    name: 'Каталония',
    flag: '🇪🇸',
    host_country: 'Испания',
    group_category: 'Другие государства',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Испания',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Испания',
      status: 'Автономное сообщество с собственной полицией (Mossos)',
      capital: 'Барселона',
      gdp: 280000000000,
      population: 7800000,
      birth_rate: 7.2,
      resource_index: 6,
      balance: 25000000000,
      support: 88.0,
      corruption: 5.6,
      specialization: 'Высокотехнологичное машиностроение, химическая промышленность, порт Барселоны'
    }
  },
  {
    key: 'auto_republika_srpska',
    name: 'Респ. Сербская',
    flag: '🇧🇦',
    host_country: 'Босния и Герцеговина',
    group_category: 'Другие государства',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Босния и Герцеговина',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Босния и Герцеговина',
      status: 'Энтитет в составе Боснии и Герцеговины по Дейтонским соглашениям',
      capital: 'Баня-Лука',
      gdp: 8200000000,
      population: 1120000,
      birth_rate: 8.0,
      resource_index: 7,
      balance: 1100000000,
      support: 92.0,
      corruption: 8.2,
      specialization: 'Гидро- и теплоэнергетика, металлургия, деревообработка, транзитные пути Балкан'
    }
  },
  {
    key: 'auto_scotland',
    name: 'Шотландия',
    flag: '🇬🇧',
    host_country: 'Великобритания',
    group_category: 'Другие государства',
    continent: 'Европа',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Великобритания',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Великобритания',
      status: 'Автономная страна в составе Соединённого Королевства с собственным парламентом',
      capital: 'Эдинбург',
      gdp: 210000000000,
      population: 5460000,
      birth_rate: 8.1,
      resource_index: 8,
      balance: 19000000000,
      support: 89.0,
      corruption: 3.8,
      specialization: 'Шельфовая нефть и газ Северного моря, финансовый хаб Эдинбурга, ветроэнергетика'
    }
  },
  {
    key: 'auto_quebec',
    name: 'Квебек',
    flag: '🇨🇦',
    host_country: 'Канада',
    group_category: 'Другие государства',
    continent: 'Северная Америка',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Канада',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Канада',
      status: 'Франкоязычная провинция Канады с признанным статусом отдельной нации',
      capital: 'Квебек',
      gdp: 390000000000,
      population: 8800000,
      birth_rate: 9.3,
      resource_index: 9,
      balance: 31000000000,
      support: 90.0,
      corruption: 4.1,
      specialization: 'Гидроэнергетический гигант Hydro-Québec, аэрокосмический кластер, цветные металлы'
    }
  },
  {
    key: 'auto_karakalpakstan',
    name: 'Каракалпакстан',
    flag: '🇺🇿',
    host_country: 'Узбекистан',
    group_category: 'Другие государства',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Узбекистан',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Узбекистан',
      status: 'Суверенная республика в составе Республики Узбекистан',
      capital: 'Нукус',
      gdp: 3500000000,
      population: 1980000,
      birth_rate: 16.2,
      resource_index: 8,
      balance: 490000000,
      support: 91.0,
      corruption: 8.4,
      specialization: 'Газодобыча на плато Устюрт, Устюртский газохимический комплекс, соледобыча'
    }
  },
  {
    key: 'auto_nakhchivan',
    name: 'Нахичевань',
    flag: '🇦🇿',
    host_country: 'Азербайджан',
    group_category: 'Другие государства',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Азербайджан',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Азербайджан',
      status: 'Нахичеванская Автономная Республика (эксклав Азербайджана)',
      capital: 'Нахичевань',
      gdp: 2100000000,
      population: 465000,
      birth_rate: 13.4,
      resource_index: 7,
      balance: 380000000,
      support: 93.0,
      corruption: 7.2,
      specialization: 'Зангезурский транспортный коридор, генерация солнечной и гидроэнергии, минеральные воды'
    }
  },
  {
    key: 'auto_gbao',
    name: 'Горный Бадахшан',
    flag: '🇹🇯',
    host_country: 'Таджикистан',
    group_category: 'Другие государства',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Таджикистан',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Таджикистан',
      status: 'Горно-Бадахшанская автономная область Республики Таджикистан',
      capital: 'Хорог',
      gdp: 700000000,
      population: 230000,
      birth_rate: 15.0,
      resource_index: 8,
      balance: 110000000,
      support: 88.0,
      corruption: 8.7,
      specialization: 'Добыча рубинов и лазурита, гидроэнергетический потенциал Памира, транзит на границе с КНР'
    }
  },
  {
    key: 'auto_bangsamoro',
    name: 'Бангсаморо',
    flag: '🇵🇭',
    host_country: 'Филиппины',
    group_category: 'Другие государства',
    continent: 'Азия',
    itemType: 'autonomy',
    typeLabel: 'Автономия · Филиппины',
    isTaken: false,
    data: {
      isAutonomy: true,
      host_country: 'Филиппины',
      status: 'Автономный регион Бангсаморо в мусульманском Минданао (BARMM)',
      capital: 'Котабато',
      gdp: 3200000000,
      population: 4400000,
      birth_rate: 18.0,
      resource_index: 7,
      balance: 420000000,
      support: 90.0,
      corruption: 8.9,
      specialization: 'Аграрный сектор, рыболовство, морские ресурсы моря Сулу, добыча никелевых руд'
    }
  }
];
